language: node_js
node_js:
  - '12'
install:
  - npm ci

cache:
  npm: false

git:
  depth: false

branches:
  only:
  - main

stages:
  # Pull request
  - name: lint
    if: type = pull_request
  - name: test (unit)
    if: type = pull_request

  # Merge on main
  - name: publish
    if: type = push AND branch = main

jobs:
  include:
    # Pull request
    - stage: lint
      script: 
        npx lerna exec -- npm ci && 
        npx lerna bootstrap && 
        npx lerna run lint
    - stage: test (unit)
      script: 
        npx lerna exec -- npm ci && 
        npx lerna bootstrap && 
        npx lerna run test:unit

    # Merge on main
    - stage: publish
      script: 
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc &&
        git remote set-url origin "https://$GH_USER:$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git" && 
        git checkout main && 
        npx lerna exec -- npm ci && 
        npx lerna publish --contents dist --yes
